name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main   # ou master, conforme teu branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Instalar dependências Composer
        run: composer install --no-dev --optimize-autoloader

      - name: Instalar dependências Node e Build
        run: |
          npm install
          npm run build

      - name: Enviar para cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          server-dir: /public_html/  # destino no cPanel
